/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DIG1_aliases.h"
#include "DIG1.h"
#include "LEDA_aliases.h"
#include "LEDA.h"
#include "LEDB_aliases.h"
#include "LEDB.h"
#include "nSW_aliases.h"
#include "nSW.h"
#include "LEDC_aliases.h"
#include "LEDC.h"
#include "LEDD_aliases.h"
#include "LEDD.h"
#include "LEDE_aliases.h"
#include "LEDE.h"
#include "LEDF_aliases.h"
#include "LEDF.h"
#include "LEDG_aliases.h"
#include "LEDG.h"
#include "LEDDP_aliases.h"
#include "LEDDP.h"
#include "DIG2_aliases.h"
#include "DIG2.h"
#include "DIG3_aliases.h"
#include "DIG3.h"
#include "DIG4_aliases.h"
#include "DIG4.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

